### ISSUE TITLE
App does not connect via Local Network Settings

### ISSUE THREAD

**Issue by Xiphan** [lgallard/qBittorrent-Controller#110]
When connecting via my WiFi network even though I have my Network SSID setup in the advanced options of the app, it doesn't connect to my server using the local IP address I have specified.

**Comment by lgallard** [comment]
Hi @Xiphan , did you check  the online documentation here http://git.io/pQB5 ? Also check how to set the app http://git.io/vOnDH, and how to enable the Web UI http://git.io/ptIr.

On the other hand, if you only get connected via WiFi to the same server, there's no need to set the SSID.

Please keep me posted!

**Comment by Xiphan** [comment]
When I am away from home I connect to my server using my external IP address and a different port which I have forwarded in my router. This works perfectly fine in your app and I am able to get in, but when I get home I have to change the external IP under Connection Host in the normal settings to my LAN IP address because the app either isn't using the IP address I have specified in the advanced options or it isn't detecting that I am connected to the local network I have specified.

**Comment by lgallard** [comment]
Did you check you can access the WebUI from your phone/device when connected to your WiFi? are your SSID hidden?

**Comment by Xiphan** [comment]
Yes, I can access the Web UI through my phone. I can even access qBittorrent through your app but only if I specify the Local IP address of my server through the standard settings, not the advanced settings.

As you can see I have gotten your app working:

![working app](https://cloud.githubusercontent.com/assets/4989354/18768401/35651e0e-8125-11e6-9d53-168e0ee5b377.png)

The problem I have is I keep having to change the IP address setting here between my external internet IP address when I am not at home, and my local IP address when I am at home:

![settings](https://cloud.githubusercontent.com/assets/4989354/18768427/5864551e-8125-11e6-882a-008f11a34e32.png)

What I would like is for the app to correctly use the advanced settings I have specified here so that when I am connected via my WiFi network it uses the Local IP address I have specified.

![advanced settings](https://cloud.githubusercontent.com/assets/4989354/18768432/5e582900-8125-11e6-8b43-fda3d7abd6b3.png)

Currently v4.4.0 of qBittorrent Controller Pro ignores the advanced settings for a local IP address. 🙁

**Comment by lgallardo-edrans** [comment]
I see your SSID has a apostrophe and white spaces. Try renaming your SSID to xian_domain and check again.

Regards,

**Comment by lgallard** [comment]
I see your SSID has a apostrophe and white spaces. Try renaming your SSID to xian_domain and check again.

Regards,

**Comment by azumukupoe** [comment]
I bought pro and I have the same issue

**Comment by lgallard** [comment]
As mentioned before, try renaming your SSID  and check again.

Regards,

**Comment by azumukupoe** [comment]
my SSID only contains hyphen and underscore
> TP-Link_SSID
