### ISSUE TITLE
Opening of endless chrome tabs

### ISSUE THREAD

**Issue by lgallard** [lgallard/qBittorrent-Controller#111]
I'm having issues adding a torrent from an RSS fee on the app.
Every time I select an RSS torrent in the app, it opens chrome and starts opening an endless amount of tabs which seem to try and download the file (figures it was endless, max count I saw before i stopped it was about 23). I've tried it a few times, but keep getting the same result. 
Am I doing something wrong?

Reported by seltzermx in [qbforums](https://qbforums.shiki.hu/index.php/topic,2655.msg23596.html#msg23596)

**Comment by lgallardo-edrans** [comment]
Extra info provided by seltzermx:

After testing with the site itself, other sites, and other RSS feeds, I have narrowed the issue down to a specific site/feed.
The feed/site that fails is nyaa.se. Selecting an item in the feed, or even selecting the magnet or torrent from the site itself in Chrome sends Chrome into an endless loop of trying to download the file but being unable to. Sorry for not having tested thoroughly before posting this.

For reference, I'm using an unlocked HTC 10 running MM.
I still have my older M8 sitting around. I'll try if there this evening and see if the behavior is the same.

**Comment by lgallard** [comment]
Extra info provided by seltzermx:

After testing with the site itself, other sites, and other RSS feeds, I have narrowed the issue down to a specific site/feed.
The feed/site that fails is nyaa.se. Selecting an item in the feed, or even selecting the magnet or torrent from the site itself in Chrome sends Chrome into an endless loop of trying to download the file but being unable to. Sorry for not having tested thoroughly before posting this.

For reference, I'm using an unlocked HTC 10 running MM.
I still have my older M8 sitting around. I'll try if there this evening and see if the behavior is the same.
