### ISSUE TITLE
[Request] App-lock

### ISSUE THREAD

**Issue by p43b1** [lgallard/qBittorrent-Controller#132]
Could it be possible adding a lock to the app in order to avoid other people to access the app even if the smartphone/tablet is unlocked?

**Comment by lgallardo-edrans** [comment]
Hi @p43b1, there are apps that lock other apps. Two random locker taken from Google Play:

* https://play.google.com/store/apps/details?id=cms.lock
* https://play.google.com/store/apps/details?id=com.getkeepsafe.applock

Therefore I don't see the need of implementing this feature in the qBittorrent Controller.

Regards,

**Comment by lgallard** [comment]
Hi @p43b1, there are apps that lock other apps. Two random locker taken from Google Play:

* https://play.google.com/store/apps/details?id=cms.lock
* https://play.google.com/store/apps/details?id=com.getkeepsafe.applock

Therefore I don't see the need of implementing this feature in the qBittorrent Controller.

Regards,
