### ISSUE TITLE
First click to qBC fails

### ISSUE THREAD

**Issue by BeecherNetworks** [lgallard/qBittorrent-Controller#144]
When I click on a magnet in my feed in Tiny Tiny RSS, the first click fails to load the torrent into qBC. The next one will work, and torrents I add after that, but next day, the same thing happens again. I don't have the same problem in Windows. How would I go about debugging this?

**Comment by lgallard** [comment]
What qBC version are you using? Version 4.5.3 added a 3 seconds delay to avoid this

**Comment by dahamsta** [comment]
4.5.3. I tested it today, clicked back and then went into qBC manually to check if it was there, no sign. Pretty sure it would have taken 3 seconds or more, and I didn't get a duplicate torrent error when I added the torrent the next time.

**Comment by lgallard** [comment]
I will check this and try to include more time for this first call

**Comment by dahamsta** [comment]
Ok, thanks.

**Comment by dahamsta** [comment]
Any progress on this? I'm still having the same problem, have to click through twice every time there's no existing session. As soon as there's a torrent in progress, all subsequent clicks go through.... until the list is empty again.

**Comment by lgallard** [comment]
@dahamsta I'm investigating the issue and trying to reproduce it. It seems it depends on the device's RAM available.

**Comment by dahamsta** [comment]
Thanks. My Sony Z5 is pretty old, but it has 3GB memory so it shouldn't be an issue; but perhaps you mean is just can't capture enough RAM at the time?

**Comment by dahamsta** [comment]
For the record, this is still happening on my new handset, a Note 8. Exact same circumstances and behaviour.

**Comment by lgallard** [comment]
Hi Adam,

I'm working on a reimplementation to replace Apache's http for Android's
Volley that should performed better.

But it's taking its time because I have to rewrite almost every function.

But there will be a change on that. Please be a little patient.

Regards,

**Comment by dahamsta** [comment]
Thanks Luis, appreciate the update.

**Comment by lgallard** [comment]
Release 4.7.0 fixes this!
