### ISSUE TITLE
[Bug] Malformed Host header when using apache. (RFC2616 section 14.23)

### ISSUE THREAD

**Issue by TheDegree0** [lgallard/qBittorrent-Controller#146]
My [qBittorrent-nox](https://github.com/qbittorrent/qBittorrent) server is passing through an [apache](https://httpd.apache.org/) server, which requires that the following header be met: [RFC 2616 14.23](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23).

It was working before, the problem appeared in recent updates. It seems that the _Host_ header is not set correctly.

From the apache logs:
`AH00550: Client sent malformed Host header: https://<my_host_appears_here>:443, referer: https://<and_here_too>:443`
[The apache error code AH00550.](https://wiki.apache.org/httpd/ListOfErrors#line-547)

**Comment by lgallard** [comment]
Hi Arnau,

That is a "feature" introduced in qBittorrent 3.3.13. Check this issue
https://github.com/qbittorrent/qBittorrent/issues/6882

This is not related with my app. In fact, the latest release included a fix
for be able to access the WebUI/API as usual.

Best regards,


Luis Gallardo
http://lgallardo.com

**Comment by lgallard** [comment]
Closed because it's not an app issue

**Comment by TheDegree0** [comment]
I don't understand why a REST API should be cross-site protected, I immediately assumed that your app was at fault, sorry :sweat_smile:!

Thanks for passing the qBittorrent thread!
