### ISSUE TITLE
Cannot add torrent file

### ISSUE THREAD

**Issue by ghost** [lgallard/qBittorrent-Controller#147]
qBittorrent x86-64 v3.3.13
qBittorrent Controller Pro v4.5.3 (Android 6.0.1, storage permission enabled)

When trying to add a torrent file from app, I get 
"The host or IP address cannot be reached. Please check your settings!"
Otherwise I can still monitor everything and delete torrents just fine. Also sent a report with the same title as this post to the developer. Same results with localhost or DDNS+port forward. 

Was able to add torrent file fine from Web UI in browser, so seems not be a problem with computer/qBittorrent configuration.

Possibility of there still being an issue with CSRF?

**Comment by lgallard** [comment]
Hi,

If the torren has spaces in its name, download it and open it from the
Downloads secton of your device.

In a future release I will address this issue.

Best regards,


Luis Gallardo
http://lgallardo.com

**Comment by bobo1724** [comment]
Thank you very much for the help.

**Comment by lgallard** [comment]
I will addressing this issue in the next release.

Regards,

**Comment by Rouzax** [comment]
Awesome, thank you for that.
