### ISSUE TITLE
Add total uploaded and downloaded

### ISSUE THREAD

**Issue by lgallard** [lgallard/qBittorrent-Controller#149]
I received this request by email from Giovanni Serafini:

"Hi Luis,

First of all, thanks for your amazing app, it really simplifies the management of a QBitorrent client!
I'd like to ask you if it's possible to add the amount of bytes transferrend, as you can see from the following screenshot:

![img_04-08-2017_02-29-37](https://user-images.githubusercontent.com/6194359/29028871-01b6f7ee-7b5c-11e7-95ac-80df745390e3.jpg)

**Comment by lgallard** [comment]
https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#get-torrent-generic-properties

**Comment by k0nk** [comment]
Hi, @lgallard!

I saw that you are very busy updating to adapt to the new web API, but can you add this long waited feature? :)

Thanks in advance!

**Comment by lgallard** [comment]
Hi @k0nk, sure thing but I'm not sure were to show it. Maybe in this section?

![DeepinScreenshot_select-area_20191217132008](https://user-images.githubusercontent.com/6194359/71014051-15d83a00-20d0-11ea-953c-048d7f7b7868.png)

**Comment by k0nk** [comment]
Yes, in this section would be fine. However, I would add below, in a new line, because would be better for small screens.

**Comment by lgallard** [comment]
@k0nk the values I can retrieve from the API are `Data downloaded this session (bytes)` and  `Data uploaded this session (bytes)`. Are you referring to those values? Download and upload totals for all torrents, not just this session is not available thru the API. Now, per torrent totals, upload and download values are shown in the torrent details.

**Comment by k0nk** [comment]
Yes. As this is the only information provided, so better than nothing.

About showing per torrent totals, it would be nice to show it directly in the torrent list, as it would make it easier to compare them and help remove those that are no longer seeding.

Thanks in advance!

**Comment by lgallard** [comment]
@k0nk the values to add in the new release will be:

![DeepinScreenshot_select-area_20191228223503](https://user-images.githubusercontent.com/6194359/71551287-5eda9900-29c2-11ea-9475-664f7309c734.png)

1. Torrent's total uploaded info (bytes). This is a total, not just for current session. 
2. Global data uploaded this session (bytes)
3. Global data downloaded this session (bytes)
4. Free space on disk (bytes)

Number 4, was requested in #197

**Comment by k0nk** [comment]
@lgallard

In my screen resolution (1080x2340) this information is really bad to read. Look:

![Screenshot_20191229-054350_1](https://user-images.githubusercontent.com/58905143/71556350-5e6bed80-2a16-11ea-9b5b-23c079f011a8.jpg)


Can you change the format that this information is shown?
I think this format below is way easier to read and will benefit more users with lower screen resolution:

Free: 300 GiB
U: 111.11 KiB/s (111 GiB) [1]
D: 222.22 KiB/s (222 GiB) [2]

**Comment by lgallard** [comment]
@k0nk I will put something like:

550.3 KiB/s - 23.5 GiB (6) 
505.4 KiB/s - 350.5 GiB (1)
Free: 3.7 GiB

It removes almost 10 characters.

**Comment by lgallard** [comment]
New release will have this format:

![DeepinScreenshot_select-area_20191229142012](https://user-images.githubusercontent.com/6194359/71560264-5f1c7800-2a46-11ea-8826-bb1eab2b171b.png)

**Comment by lgallard** [comment]
@k0nk check release 4.7.6!

**Comment by lgallard** [comment]
@k0nk this how it looks on my phone:
![Screenshot_20191229-153223](https://user-images.githubusercontent.com/6194359/71561228-97c24e80-2a52-11ea-8c25-cf8e988eb6dd.png)

I think I have to include a footer to move at least Free Space on disk

**Comment by k0nk** [comment]
That is how it looks on mine:

![Screenshot_20191229-155410_1](https://user-images.githubusercontent.com/58905143/71561393-a3167980-2a54-11ea-82b6-ec6a35dcaaa6.jpg)

This is a little bit more readable, but I think that when those numbers change, the same thing will happen again.

**Comment by k0nk** [comment]
@lgallard I noticed now that upload and download got  their places swapped. 😳 

![Screenshot_20191230_134841](https://user-images.githubusercontent.com/58905143/71591584-b0db0600-2b0b-11ea-9b9d-8779853170b3.jpg)

**Comment by lgallard** [comment]
Fixed in the 4.7.7 release!

**Comment by k0nk** [comment]
Now everything is ok.

![Screenshot_20191230_174750](https://user-images.githubusercontent.com/58905143/71600169-91a0a080-2b2c-11ea-9aa9-b91563be547f.png)
Thank you! 👍
