### ISSUE TITLE
Feature request - delete files on torrent delete

### ISSUE THREAD

**Issue by Rouzax** [lgallard/qBittorrent-Controller#159]
Great app and paid for the pro version.
Could you maybe add the option to delete the actual downloaded files when a torrent is deleted?

**Comment by rhincredible** [comment]
I second this request, this is a key feature.

**Comment by lgallard** [comment]
You have two options: _Delete_  (trash bin icon) and _Delete data_ (X icon). Boths delete the torrent file, but the latter also deletes the downloaded files!
