### ISSUE TITLE
Qbittcontroller , cant list files on android

### ISSUE THREAD

**Issue by dunken22** [lgallard/qBittorrent-Controller#162]
Hi 

Ran into some very wierd problem , 
Did install the qbittorrent controller on a new android device , but it wont list the torrents at all 

Did change password in the webgui to another , did change password on the other android that been working just fine before , same stuff on that device , cant list the torrents at all 

when logging into the webgui
http://192.168.0.9:20355/

working just fine can see all items etc 

??

**Comment by lgallard** [comment]
@dunken22 Did you double checked your settings? Don't use username or password with white spaces!
