### ISSUE TITLE
4.5.9 crashing when changing port

### ISSUE THREAD

**Issue by dudeman27** [lgallard/qBittorrent-Controller#164]
I just updated to version 4.5.9 on the Pro copy. After upgrading, the app would periodically crash in the background and immediately crash when attempting to open the app.

The only way I could get it to start is to clear app data. Through trial and error I figured out I could re-enter all of my normal server settings. The moment I change the port from 8080 to 8082, the app starts crashing again and I can't get back in without clearing app data.

I sent crash feedback through my phone already. Please let me know if you need more info.

qBittorrent v4.1.1 (64-Bit)
Qt: 5.10.1
Libtorrent: 1.1.7.0
Boost: 1.67.0

**Comment by lgallard** [comment]
Please update to version 4.6.3. Regards!

**Comment by lgallard** [comment]
By the way, thanks for the information. I really appreciate this kind of information because it helps me to determine what is causing the issues for your Android version.

**Comment by dudeman27** [comment]
No problem. I'm getting the same problem on 4.6.3. If I clear app data I can get it to run. Change the port and it starts crashing again. Change about everything besides that and the app doesn't crash.

I also receive errors about trying to retrieve a new API, but I assume that's because it can't connect yet (because of the port). I can post those if needed too.
