### ISSUE TITLE
Android/Linux/Vpn

### ISSUE THREAD

**Issue by nph479** [lgallard/qBittorrent-Controller#165]
I dont knew if I can ask Questions here but I do it anyway =).

I have setup WebUi with my Android phone, it works fine with my local ip on the server. But when I try to come from outside local network with my external ip it do not work.

What am I suppose to do, get ddns ore am I doing something wrong?

**Comment by lgallard** [comment]
That's right! You have to access using you public IP address.

**Comment by nph479** [comment]
I have done this, same settings in the server and the Android, the router have 8080/8999 in the UPnP service list.
If I just change the Ip to local and there is the torrents list.

**Comment by lgallard** [comment]
Configure a second server for your public access!

**Comment by nph479** [comment]
Ok. Now I try both ip "79.000.127.96" "177.000.1.15" is this correct?
Local ip works ok but public not, I also try in my computer web-browser and Local ip ok but not Public ip.

**Comment by lgallard** [comment]
Take into account that probably your public IP is set to your router, therefore you must NAT your traffic to your PC. Check your router settings to achieve that!

**Comment by nph479** [comment]
Now I have try with Virtual server with Port 8080 open and also Port-triggering with Port 8080 but outside Lan I cant get connection.
I am probably to stupid but do you have other suggestion? Is there a tutorial for all this?

**Comment by lgallard** [comment]
You have to NAT you traffic.
