### ISSUE TITLE
qBittorrent-Controller Pro doesn't work anymore with 4.1.3 qbittorrent version

### ISSUE THREAD

**Issue by smayor84** [lgallard/qBittorrent-Controller#166]
Hi, with the last update app can't connect anymore to qBittorrent. Both connections (inside LAN and outside LAN) return message can't connect please verify your IP host. Am I the only one with this problem?
thanks

**Comment by rbtmarshall** [comment]
I also have this issue.

**Comment by lgallard** [comment]
qBController v4.7.0 fixes it!
