### ISSUE TITLE
insecure gradlew

### ISSUE THREAD

**Issue by IzzySoft** [lgallard/qBittorrent-Controller#167]
In case this app is still under active development (despite having seen no commit for about a year): F-Droid's lint just complained about an "insecure gradlew":

```
Found plain HTTP URL for gradle repository:
build/com.lgallardo.qbittorrentclientpro/app/build.gradle
repositories {
    mavenCentral()
    maven {
        url "http://dl.bintray.com/lukaville/maven"
    }
gradle build uses plain HTTP URLs for repositories!  This is insecure!
https://max.computer/blog/how-to-take-over-the-computer-of-any-java-or-clojure-or-scala-developer/
```

Bintray can "speak HTTPS", so the fix should be as simple as replacing `http://` by `https://`. Thanks!

**Comment by IzzySoft** [comment]
@lgallard just wondering: _is_ this project still maintained?

**Comment by lgallard** [comment]
@IzzySoft it is. I'm working on a release to support qBittorrent 4.2.0+. I would include a fix for this in this release.

**Comment by IzzySoft** [comment]
@lgallard Great, thanks for your answer! Then we'll look forward to the next tag (which hopefully triggers the next F-Droid release fine).
