### ISSUE TITLE
Update Wiki for Self Signed Certificates

### ISSUE THREAD

**Issue by dudeman27** [lgallard/qBittorrent-Controller#172]
I use sslforfree.com and need to update my certs to BKS with portecle. I always forget the steps so I reference this:
https://github.com/lgallard/qBittorrent-Controller/wiki/Using-Self-Signed-Certificates

The screenshots are no longer available. It would be nice if the screenshot locations could be updated, and the guide updated with text as well in case the screenshots become unavailable again.

**Comment by lgallard** [comment]
Fixed! Check https://github.com/lgallard/qBittorrent-Controller/wiki/Using-Self-Signed-Certificates again!
