### ISSUE TITLE
order by speed is incorrect.

### ISSUE THREAD

**Issue by csy45250584** [lgallard/qBittorrent-Controller#175]
when i order my torrents by upload speed ,the torrent which's upload speed is 1.1MB/s  belows to the torrent which's upload speed is 900KB/s.
i  think that maybe the 1.1MB/s  is in incorrect position.

**Comment by lgallard** [comment]
This will be fixed in the new release. Commit 08bbd2f8d86fdc28c8f25abe0e9edf70d682a059 fixes it!

**Comment by lgallard** [comment]
Release V4.7.0 fixes it!

**Comment by csy45250584** [comment]
thx！
