### ISSUE TITLE
Can't connect to server - Infinite loading

### ISSUE THREAD

**Issue by Mr-DeWitt** [lgallard/qBittorrent-Controller#184]
From the last version of qBittorrent Controller (4.7.1 Android) I cant connect to my server.
It doesn't show any error, just loads indefinitely with the spinning loader on the screen.
If I try to connect with wrong credentials (intentionally), it does the same and doesn't show any error, so it seems the program stuck before authentication.

I've tried with qBittorrent v4.1 and V4.2 too, none of them worked.

**Comment by lgallard** [comment]
Do you have HTTPS enabled?

**Comment by Mr-DeWitt** [comment]
Yes, I use a reverse proxy with a valid certificate.

**Comment by lgallard** [comment]
HTTPS Is not yet implemented. I have to work on the.

Regards,

**Comment by Mr-DeWitt** [comment]
The last version of the app has solved the issue.

**Comment by lgallard** [comment]
HTTPS was implemented in 4.7.3. Regards,
