### ISSUE TITLE
qBittorrent Controller Pro not working anymore with qbittorrent-nox 3.3.7-3

### ISSUE THREAD

**Issue by rickglyn** [lgallard/qBittorrent-Controller#188]
I am getting error "Host not found" with qBittorrent Controller Pro version 4.7.3 the last few days. I have had no problems with using the app over many months of use. The server is on my local network and there is no problem accessing it with the regular Web page option on the same internal IP.

**Comment by lgallard** [comment]
Hi, qBController versions 4.7.x are for qBitorrent 4.1.x and 4.2.x. If you are using lower versions use qBController 4.5.8 (free) or 4.6.4 (pro). Both available here https://github.com/lgallard/qBittorrent-Controller/releases/tag/v4.5.8. Another option is to upgrade your qBittorrent to 4.2.x.
