### ISSUE TITLE
Connection OK but torrent list missing

### ISSUE THREAD

**Issue by Randomico** [lgallard/qBittorrent-Controller#200]
Hi,
Since the few last releases in the new qbt API, i can connect and even send magnetic links to the server but the app doesn't list any of the torrents. Already tried reinstalling the app completely with no success.

Tested with:
Server version: 4.2.0 and 4.2.1
App version: 4.7.5 and couple earlier releases.
Android version: 6.0.1

![Screenshot_2019-12-29-02-43-43](https://user-images.githubusercontent.com/48738273/71553069-7e37ed00-29e7-11ea-9f32-089a05628413.png)

**Comment by lgallard** [comment]
Hi,

On categories select Tudo. If you have a category selected and there's not
torrents for the current state you won't see any torrents.

Regards,

**Comment by Randomico** [comment]
I've tested in all categories to see if any of the server torrents appear but with no success.
The print i sent is set on "Tudo" category and it's possible to see activity on the server through the upper bar but the torrent list won't show.
Just to add, im using https with self signed certificate.

**Comment by lgallard** [comment]
That's odd. Select Tudo and Tudo, for torrents selection and Categories

**Comment by Randomico** [comment]
That did the trick. Didn't notice the existence of this category (Etiqueta for me) setting, thought we were talking about the torrent states.
Appreciate the support.

**Comment by lgallard** [comment]
Thank for reporting, I will include a better message, something like
"Torrents not found for this category"

Regards!
