### ISSUE TITLE
"Host not found" if using subdomain

### ISSUE THREAD

**Issue by csutcliff** [lgallard/qBittorrent-Controller#217]
IP access works, domain.tld works, sub.domain.tld produces "Host not found". Tested multiple domains. Web browser access works fine. Using HTTPS if it helps.

**Comment by lgallard** [comment]
@csutcliff  I just released version 4.84, removing the host header. I try with a subdomain and it works. My subdomain was `test.qbcontroller.org`. 

Please check this new version!

**Comment by csutcliff** [comment]
Working for me also, thanks!
