### ISSUE TITLE
Connection Error using Hostname

### ISSUE THREAD

**Issue by eldonatienza** [lgallard/qBittorrent-Controller#218]
I've been encountering a connection error when I'm trying configure the settings in the app using my laptop hostname but works fine when I use the IP address, i'm having internet access problems when i try to get a static IP so I just want to leave my laptop ip in dynamic. Anyone have an idea of what might be the problem?

**Comment by lgallard** [comment]
@eldonatienza you have to NAT your traffic to your qBitorrent server on your PC and use your public IP and port.  Another alternative is to use a DNS like DynDNS or noip to use your  public IP address dynamically.

**Comment by lgallard** [comment]
@eldonatienza I just released version 4.84, removing the host header. I try with a subdomain and it works. My subdomain was `test.qbcontroller.org`. 

Please check this new version!
