### ISSUE TITLE
qBittorrent-Controller with VPN

### ISSUE THREAD

**Issue by MihailCosmin** [lgallard/qBittorrent-Controller#227]
Is it possible to use qBittorrent-Controller if on my PC I am downloading through a VPN?

**Comment by lgallard** [comment]
Yes, just use the IP address assigned to your qBittorrent PC by the VPN

**Comment by MihailCosmin** [comment]
By now I have tried all IPs showed with ifconfig (I am using linux). Several work if I try to open the IP+port (8080) with a browser directly from the computer. But none work on my phone, neither on a browser or in the app.

From my PC, these work:
127.0.0.1 - But this definitely couldn't work on my phone...
10.26.0.18 - This is given by the VPN
192.168.2.103 - This is given by the wifi network.

**Comment by MihailCosmin** [comment]
Tried without VPN connected.
Now I only have 192.168.2.103 when running ifconfig.
And the qBittorrent-Controller (192.168.2.103:8080) works on my PC, but not on my phone.
Is there any reason for that ?

**Comment by MihailCosmin** [comment]
Ok, finally solved it!

First issue was the Linux firewall. I had Gufw Firewall on. Solution for this was to turn it off, or add a rule for port 8080.

After this 192.168.2.103:8080 (without VPN and with VPN also) started working in the browser on my phone, but in the app I was getting "Host not found!" error
Solution for this was to update the qbittorrent from my PC to the latest version.

Now it works in app also!
