### ISSUE TITLE
qBController Pro can't connect from externel IP using no-ip or duckdns

### ISSUE THREAD

**Issue by morfei1** [lgallard/qBittorrent-Controller#243]
The app can't connect for example: mydomain.ddns.net or mydomain.duckdns.org. from external IP.

If I setup my internal IP in qBController app and then use a VPN, I can access the server but it's inconviniant for me to use VPN whenever I need to access my qbitorrent.

Everything is working and setup corectly, because I have access to the qbitorrent server from mydomain.ddns.net or mydomain.duckdns.org when using Chrome browser from externel IP.

I have read the WiKi but "Connection Host" with domain does not seams to work.

Regards!

**Comment by lgallard** [comment]
@morfei1 in the pro version you can have set a server for your local network and another one for the external domain!

**Comment by morfei1** [comment]
Now, actually it's working with your help. External and local connection should have separate profiles (server 1 - external settings, server 2 - local settings)

Thank you for the fast response.
