### ISSUE TITLE
After a few minutes of normal operation it closes without an apparent reason

### ISSUE THREAD

**Issue by gcarreno** [lgallard/qBittorrent-Controller#250]
Hey @lgallard 

I was finally able to send a report from the Nexus 7!! Sometimes it goes boom and the crash is not picked up by the Nexus crash reporter.
Dunno how you can find it on the Google but my associated email there is `guscarreno` at the Google Email thingamabob :smile:.

Not sure if it relates to #249, but you now have all the specs and stuff needed for a more in-depth debug session of my Nexus 7.

Many thanks!!

Cheers,
Gus

**Comment by lgallard** [comment]
#266 has more info abour this issye. Closing this one to avoid duplicates
