### ISSUE TITLE
trouble with semicolon in rss url

### ISSUE THREAD

**Issue by thetrompf** [lgallard/qBittorrent-Controller#44]
Hi
For some reason I am member of a site that uses `;` in the query string, which results in qbittorrent controller truncated everything from that semi colon

`site.con/rss?download;7;u=2305860;tp=0`

When I add this as an rss feed I get an error that it couldn't download the feed and the url is changed to

`site.com/rss?download`

It probably works if I url encode the semi colons myself, but haven't tried it yet.

**Comment by thetrompf** [comment]
Nope even if I manually url encode both `;` and `=` it doesn't work

**Comment by lgallard** [comment]
I included the issue in the next release, so it will fixed as soon as possible.

**Comment by lgallard** [comment]
I found the problem. RSS feed and its properties are stored one per line using semicolon as delimiter, therefore if you add an URL with semicolons you will be breaking the format.

As a possible solution I will try to encode the URL before store the RSS feed.

**Comment by thetrompf** [comment]
That sounds great, looking forward to test it :)

**Comment by lgallard** [comment]
Fixed in testing. It will be available in the next upcoming release.
