### ISSUE TITLE
Include "Sort by Added on" and " Sort by Completed on"

### ISSUE THREAD

**Issue by lgallard** [lgallard/qBittorrent-Controller#45]
Include "Sort by Added on" and  in "Sort by Completed on" among sorting options

**Comment by lgallard** [comment]
This cannot be done unless the "Added on"  is included in the torrent generic properties fields as explained here:

https://github.com/qbittorrent/qBittorrent/issues/3769
https://github.com/qbittorrent/qBittorrent/issues/2255

**Comment by sledgehammer999** [comment]
@lgallard I suggest you open a new issue on our tracker detailing your requirements. The dev team might be able to help/implement. @buinsky @ngosang

**Comment by lgallard** [comment]
@sledgehammer999 thanks. 

With the addition_date (when this torrent was added) and the completion_date (torrent completion date) are enough.

I will implement the sorting option in the next release.

**Comment by lgallard** [comment]
I don't know if I should ask it here or open another issue, but even though the _addtion_date_ and _comletation_date_ exists, that information can only be got from the torrents generic properties, and not in the torrent list. It would be nice to have it in the torrent list.

Why? Because those values can be used to filter the torrent list. But to sort them, the app must make a request for each torrent on the torrent and then filter them. This means, if you have 100 torrents and  want to sort by _comletation_date_ you must get the torrent list and then iterate over that list to make 100 request, one per torrent.

If you check µTorrent API,  it has the "Created on" (Added on") and "Completion on" in the torrent list:

        "torrents": [
                [ HASH (string),
                STATUS* (integer),
                NAME (string),
                SIZE (integer in bytes),
                PERCENT PROGRESS (integer in per mils),
                DOWNLOADED (integer in bytes),
                UPLOADED (integer in bytes),
                RATIO (integer in per mils),
                UPLOAD SPEED (integer in bytes per second),
                DOWNLOAD SPEED (integer in bytes per second),
                ETA (integer in seconds),
                LABEL (string),
                PEERS CONNECTED (integer),
                PEERS IN SWARM (integer),
                SEEDS CONNECTED (integer),
                SEEDS IN SWARM (integer),
                AVAILABILITY (integer in 1/65535ths),
                TORRENT QUEUE ORDER (integer),
                REMAINING (integer in bytes),
                DOWNLOAD URL (string),
                RSS FEED URL (string),
                STATUS MESSAGE (string),
                STREAM ID (string),
                => ADDED ON (integer in seconds), <=
                => COMPLETED ON (integer in seconds), <=
                APP UPDATE URL (string) ],

Another solution could be to have a filter for _comletation_date_ and addition_date (like the all, downloading, completed, paused, active, inactive filters),and have the torrent list sorted from qBittorrent.

@buinsky @ngosang @sledgehammer999 what do you think?

**Comment by sledgehammer999** [comment]
I am removing myself from notifications, since I am not involved with the web API.
