### ISSUE TITLE
Deleting a Torrent File - Should ask for a confirmation if the admin would like to delete the data file along with the Torrent file

### ISSUE THREAD

**Issue by praveena87** [lgallard/qBittorrent-Controller#49]
Currently while deleting a torrent file from the controller, it does not ask for a confirmation whether i would like to delete the data file along with the torrent file. Instead it simply deletes the torrent file from the qBitTorrent database leaving the downloaded file as it is. The Web-interface however has a tick-box in the confirmation dialogue box, which is unticked by default. 
I think the controller should also provide this option.

**Comment by lgallard** [comment]
Hi @praveena87 

You can delete torrent and its data using the "x" button in the torrent details as shown here:

![Delete with data](https://c1.staticflickr.com/1/683/22878550806_e6c39ea665_z.jpg)

Then you will receive a warning message that the torrent file and its data will be delete from hard disk:

![Delete with data message](https://c2.staticflickr.com/6/5675/22716536520_2cd4ddcb65_z.jpg)

The WebUI has tick-box, but the Android app has two buttons, the trash-bin button for deleting just the torrent file and the "x" button to delete the torrent file and its data.

**Comment by lgallard** [comment]
I'm closing this issue because the function do exist as show above!
