### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by pappabetalar** [lgallard/qBittorrent-Controller#56]
Hi

I would like the option to change language in the app, is this possible to add?

**Comment by lgallard** [comment]
Hi @pappabetalar. Language in Android apps is set according to the device's locale. Just take a look to apps like Gmail or Chrome where you won't see that option. The idea behind this is to have consistency between apps and avoid unnecessary settings in every single app.

 
Therefore this is a "no"

Best regards!
