### ISSUE TITLE
After adding a new torrent, the "Torrent sent!" pop-up message is displayed every time you re-orient the screen

### ISSUE THREAD

**Issue by vermian** [lgallard/qBittorrent-Controller#70]
Happens when re-orienting the phone as in landscape -> portrait or vice versa.

**Comment by lgallard** [comment]
Hi @vermian thanks for the report. I've seen that behaviour a couple of time. I have to figure how to fix it.

Regards!

**Comment by lgallard** [comment]
It seems it was fixed when fixing #100
