### ISSUE TITLE
HTTPS with with trusted certificate seems to be broken

### ISSUE THREAD

**Issue by thetrompf** [lgallard/qBittorrent-Controller#75]
I have a server publicly accessible, encrypted with a certificate issued by startssl.com.
When opening the web interface in a browser it works fine and Chrome has no problem with the certificate nor the issuer's certificate for that matter.
But after one of the recent updates of the app, (2-3 months or so) I get the following toasts "A network failure" - "IP address / hostname could not be reached".
Since the certificate is not self-signed I have not provided keystore nor keystore password.

**Comment by thetrompf** [comment]
I "fixed" the problem, or I found a workaround. Apparently qbittorrent-nox does not comply the strict SSL policies chrome on mobile requires, so I have fabricated a workaround using nginx to resolve the SSL layer and then proxy pass to the qBittorrent Web UI via http, so no SSL enabled at the qBittorrent Web UI end.

`/home/<qbittorrent-user>/.config/qBittorrent/qBittorrent.conf`:
```
...
WebUI\Port=8081
WebUI\HTTPS\Enabled=false
...
```

`/etc/nginx/sites-enabled/qbittorrent`
```
server {
        listen 8080 ssl;

        # Make site accessible from https://qbittorrent.example.com:8080
        server_name qbittorrent.example.com;

        location / {
                proxy_pass http://localhost:8081;
        }

        ssl_certificate /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;

        ssl_session_timeout 10m;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES$

        ssl_dhparam /etc/nginx/ssl/dhparams.pem;
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:10m;
}
```

I used [startssl.com](https://www.startssl.com/) to get a free SSL certificate, and [weakdh.org](https://weakdh.org/sysadmin.html#nginx) to setup nginx SSL correctly.

**Comment by lgallard** [comment]
@thetrompf but this approach disable doesn't disable https from the app to qBittorrent? If you are using the app to connect from Internet all will be in plain text (http).

I guess this issue can be related to the strict verification when using https from java (Android) side.  Did you tried to generate a BouncyCastle Keystore (BKS) with your certificates, no matter if it's not self-signed? Here you can check how to create the keystore using Portecle or keytool from the CLI and how to set it up in qBittorrent Controller https://github.com/lgallard/qBittorrent-Controller/wiki/Using-Self-Signed-Certificates

**Comment by thetrompf** [comment]
That's exactly the point (not to disable https), as it turns out, it is not qBittorrent-Controller's, it is a combination of an update to Android subsystem which removed the support for old SSL ciphers and qbittorrent-nox only supporting outdated SSL ciphers.

The way I have getting  "legit" SSL certificates (not self-signed) to work, is using nginx handle the SSL layer see the reference to weakdh.org and proxy plain http to qbittorrent-nox so I now can use more secure SSL ciphers which Android supports thus qBittorrent Controller as well.

**Comment by thetrompf** [comment]
In conclusion it's an Android "problem" or it has on purpose removed support for legacy insecure SSL ciphers, which qbittorrent-nox does not yet support.

You can however use old SSL ciphers by using self signed certificates and keystores as you described above.

**Comment by lgallard** [comment]
I see. Then it should be an issue for qBittorrent project so they should update their ciphers.

**Comment by lgallard** [comment]
I guess the Android "problem" is an enhance of security, like us or not.

**Comment by thetrompf** [comment]
I discovered that yes. But now I have at least provided a workaround if you
want to use SSL certificates issued by trusted authorities, if anyone was
interested. :)

**Comment by thetrompf** [comment]
> I guess the Android "problem" is an enhance of security, like us or not.
Yes. It is a good thing, security above all.

Which is why I share my solution, it provides a more secure SSL connection as it is supported by newer Android policies.

**Comment by lgallard** [comment]
@thetrompf I added your workaround to the wiki https://github.com/lgallard/qBittorrent-Controller/wiki/HTTPS-with-with-trusted-certificate.

Thanks for sharing your findings!

**Comment by thetrompf** [comment]
No problem sir :+1:

**Comment by krichter722** [comment]
Why has this been closed. There's only a workaround provided, but the problem isn't fixed, right?

**Comment by lgallard** [comment]
@krichter722 because is not an app issue. As discussed above, it's an security added by Android.
