### ISSUE TITLE
￼￼App is not working on Android 6.0.1

### ISSUE THREAD

**Issue by lgallard** [lgallard/qBittorrent-Controller#87]
The problem is, the app not show torrents and not show any errors, after adding a host.

Issue reported by Gerson and Kara by email.

**Comment by lgallard** [comment]
Working on:

Android N
Android 6.0

I haven't found an emulator with Android 6.0.1 to reproduce the issue

**Comment by Mattia98** [comment]
Working for me! 
Nexus 5x with Android 6.0.1

**Comment by lgallard** [comment]
@Mattia98 thanks for your feedback. This issues have been reported only on Motorola devices, therefores is good to know is not affecting all Android 6.0.1 devices.

**Comment by lgallard** [comment]
This issue can be related to #89

**Comment by lgallard** [comment]
There is an issue when adding your account the first time, if by mistake you set your account wrongly (username or password), the app tries to connect several times without showing any error or message. Because these authentication failures the qBittorrent server bans your device's IP address. To check if you have been banned, try to reach your qBittorrent WebUI from your Android device browser.

To remove the ban and get connected, the workaround is the following:

1. Check your account settings (specially the password that is hidden)
2. Close the Android app completely. Even remove it from the recent app list.
3. Restart the qBittorrent WebUI interface (by disable/enabling or by closing/opening qBittorrent) to remove the ban. 
4. Launch the app one more time. It

**Comment by lgallard** [comment]
I just updated a new version. I hope it fixed the issue.

Please keep me posted!

Regards,

**Comment by lgallard** [comment]
Closing issue. If there is more information, the issue can be reopened.
