### ISSUE TITLE
Download status not working on Android 6.0.1

### ISSUE THREAD

**Issue by lgallard** [lgallard/qBittorrent-Controller#94]
When I click on each torrent, the details for each of them show it's downloaded 357mb out of 600mb, regardless of their actual status. 
I've cleared cache, data, uninstalled and reinstalled. Still the same. 

The device is:

Samsung S7 with Android 6.0.1 with June security patch

Reported by Rob via email.

**Comment by pzwestside** [comment]
Same... Nexus 6P 6.0.1

**Comment by lgallard** [comment]
@pzwestside are you still having this issue? Have you tried it on Android 7.0?

By the way, do you have any customization on your phone, any language or regional setting I should be aware of?

Regards,

**Comment by lgallard** [comment]
Rob reported (via email) the issue is not longer happening. I will close the issue, but if it happens again it can be reopen.
