### ISSUE TITLE
Is there something wrong with file association?

### ISSUE THREAD

**Issue by akaneko252** [lgallard/qBittorrent-Controller#95]
Hi.

When I download torrent file by chrome, some websites are OK but strange in "https://www.nyaa.se/". The DL can't start and keep opening new tabs in browser, it can open over 100 tabs in a few minutes. And the qbc app will autorun. It's OK after uninstall qbc. Firefox can DL torrent file but when you select by qbc it also can't work.

And it has problem to stat the torrent file. When I run the torrent in FileManager by qbc, sometimes it can work, but sometimes it can't upload wiht the error " The host or IP address cannot be reached ".

**Comment by lgallard** [comment]
Hi @akaneko252 

The file association is handled by Android. Every app declares what kind of file association it serves and the user at the end decides the default app.

Regarding your issue, I also have chrome and qBController installed on a tablet and two phones, and I haven't seen this behavior.

Did you try to uninstall and reinstall Chrome as well?

Regards,

**Comment by akaneko252** [comment]
Hi.

It's nothing change when reinstall chrome, but uninstall qbc.Both android emulator and phone are the same result. I just set chrome as defult download app. Not all webs like this but the one I reported. 

Did you try the same web?

Good weekend.

**Comment by lgallard** [comment]
Hi,

Chrome is not meant to handle torrent files, instead set qBController.

If you still want to use Chrome to download your torrent files, the long press over the link and select download link.

Regards,

**Comment by akaneko252** [comment]
Hi.

Oh! I always though the add in qBC is only magnet links support. Now I don't need to download torrent files and upload to BT client any more.

I find it if a device intall Chrome and qBC, Chrome can't start download from the web. Download link is no use in Chrome.

Regards,
